### ISSUE TITLE
Does cmptxtrender have tracing turned on?

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/palaso-python#10]
Starting recently, `smith test` is adding huge numbers of unnecessary blank lines to the build log.  In some cases it is so many lines that my terminal buffer is completely consumed with them. They can also be seen in TeamCity build logs, e.g., Doulos:

![image](https://user-images.githubusercontent.com/6842108/234653364-24aaaf15-88ff-4691-bc18-384c2f589717.png)

@devosb wrote:

>I suspect that when @mhosken improved cmptxtrender to handle RTL better he left tracing enabled. At least that was what @tim suspected when I talked with him … I think if smith test was run on Jammy those extra lines would not be blank, they would be filled with tracing information.

**Comment by devosb** [comment]
I was incorrect with both statements:
- The extra lines do not seem to be due to tracing, but rather a print buffer statement that was [added](https://github.com/silnrsi/palaso-python/commit/2040f6056473ebe28271a8265e4b0c66c29a9adc#diff-e6e3204e0251ca6e1d5552cefc2a7282d81eb089ede99ceb18bb84283875c406R318) when trying to fix https://github.com/silnrsi/palaso-python/issues/
- Even on Ubuntu Jammy the print buffer statement outputs blank lines
